### ISSUE TITLE
Search Expansion

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#13] opened 2018-09-16 20:26 UTC
An expansion to the search capablities, including but not limited to: 
Positions through users
User through positions
Training Materials through positions 
Positions Through training materials 
Users through managers (can only be done by a system admin or a senior manager or higher)

**Comment by Tadukoo** [comment] 2018-11-09 22:00
Duplicate of too much to list (all searches)

**Closed by Tadukoo** 2018-11-09 22:00 UTC
Labels: Duplicate
