### ISSUE TITLE
Training Histories can only be viewed

### ISSUE THREAD

**Issue by RcVincent** [RcVincent/CS-481-Senior-Software#40] opened 2018-09-17 00:27 UTC
Regardless of who views a training history, no one can edit it. These lists are view only. System admins, users, managers: no one can edit the data displayed. Not even HR can edit this information. 

Training histories will be a list of some sort and linked to a user profile and may have their own database tables.

**Comment by Zackeree** [comment] 2018-11-09 21:59
Duplicate of #43

**Closed by Zackeree** 2018-11-09 21:59 UTC
Labels: Feature
